import sqlite3
from db import db

class UserModel(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key = True)
    #due to primary key, id is autogenerated.
    username = db.Column(db.String(80))
    password = db.Column(db.String(80))

    def __init__(self, username, password):
        self.username = username
        self.password = password

    def save_to_db(self):
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self):
        #added by bmt, not part of course, refer L86@5:25
        db.session.delete(self)
        db.session.commit()

    # NB: since find_by_username does not use self, make it a classmethod
    @classmethod
    def find_by_username(cls, username):
        return cls.query.filter_by(username=username).first()
        #SELECT * FROM users WHERE username=username LIMIT 1

    @classmethod
    def find_by_id(cls, _id):
        return cls.query.filter_by(id=id).first()
        #SELECT * FROM users WHERE id=id LIMIT 1
